version: 2
updates:
  - package-ecosystem: docker
    directory: /
    groups:
      docker:
        patterns: ['*']
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns: ['*']
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    groups:
      gomod:
        patterns: ['*']
    schedule:
      interval: weekly
