run:
  tests: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - forbidigo
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  disable:
    - godox  # Unfortunately we have some of these
    - nonamedreturns  # Used in some providers, we should restructure the code to not need it
    - revive  # Need to have a good look at its configuration
    - wastedassign  # Does not yet support generics

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-files:
    - ".*\\.pb\\.go$"
    - "scripting/parser/herd_.*\\.go$"
  exclude-rules:
    # This needs to be disabled until we update the protobuf dependency
    - path: provider/plugin/common/grpc.go
      linters:
        - staticcheck
    # We ignore all i/o errors, needs a dedicated fix
    - path: ui.go
      linters:
        - errcheck
    # This file is deliberately not in alphabetical order. Will be fixed when
    # ssh key discovery and host key discovery are separated
    - path: cmd/herd/.*_providers.go
      linters:
        - gci

linters-settings:
  forbidigo:
    forbid:
      - ^fmt\.Print.*
      - ^spew\.Dump
  gci:
    sections:
      - standard
      - prefix(github.com/seveas/herd)
      - default
    custom-order: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      # TODO try the other tags
    disabled-checks:
      - ifElseChain
      - hugeParam
      - equalFold
      - rangeValCopy
  gofumpt:
    extra-rules: true
  grouper:
    import-require-single-import: true
  prealloc:
    simple: false
    for-loops: true
  predeclared:
    q: true
  stylecheck:
    checks:
      - all
      - -ST1003  # FIXME: We have many miscapitalized names
      - -ST1005  # Our error messages go straight to the user and are full sentences
