// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: provider/plugin/common/plugin.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProviderPluginClient is the client API for ProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderPluginClient interface {
	SetLogger(ctx context.Context, in *SetLoggerRequest, opts ...grpc.CallOption) (*SetLoggerResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	SetDataDir(ctx context.Context, in *SetDataDirRequest, opts ...grpc.CallOption) (*SetDataDirResponse, error)
	SetCacheDir(ctx context.Context, in *SetCacheDirRequest, opts ...grpc.CallOption) (*Empty, error)
	Invalidate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Keep(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
}

type providerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderPluginClient(cc grpc.ClientConnInterface) ProviderPluginClient {
	return &providerPluginClient{cc}
}

func (c *providerPluginClient) SetLogger(ctx context.Context, in *SetLoggerRequest, opts ...grpc.CallOption) (*SetLoggerResponse, error) {
	out := new(SetLoggerResponse)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/SetLogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) SetDataDir(ctx context.Context, in *SetDataDirRequest, opts ...grpc.CallOption) (*SetDataDirResponse, error) {
	out := new(SetDataDirResponse)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/SetDataDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) SetCacheDir(ctx context.Context, in *SetCacheDirRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/SetCacheDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) Invalidate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/Invalidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) Keep(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/Keep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerPluginClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/common.ProviderPlugin/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderPluginServer is the server API for ProviderPlugin service.
// All implementations must embed UnimplementedProviderPluginServer
// for forward compatibility
type ProviderPluginServer interface {
	SetLogger(context.Context, *SetLoggerRequest) (*SetLoggerResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	SetDataDir(context.Context, *SetDataDirRequest) (*SetDataDirResponse, error)
	SetCacheDir(context.Context, *SetCacheDirRequest) (*Empty, error)
	Invalidate(context.Context, *Empty) (*Empty, error)
	Keep(context.Context, *Empty) (*Empty, error)
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	mustEmbedUnimplementedProviderPluginServer()
}

// UnimplementedProviderPluginServer must be embedded to have forward compatible implementations.
type UnimplementedProviderPluginServer struct {
}

func (UnimplementedProviderPluginServer) SetLogger(context.Context, *SetLoggerRequest) (*SetLoggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogger not implemented")
}
func (UnimplementedProviderPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedProviderPluginServer) SetDataDir(context.Context, *SetDataDirRequest) (*SetDataDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDataDir not implemented")
}
func (UnimplementedProviderPluginServer) SetCacheDir(context.Context, *SetCacheDirRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCacheDir not implemented")
}
func (UnimplementedProviderPluginServer) Invalidate(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedProviderPluginServer) Keep(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keep not implemented")
}
func (UnimplementedProviderPluginServer) Load(context.Context, *LoadRequest) (*LoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedProviderPluginServer) mustEmbedUnimplementedProviderPluginServer() {}

// UnsafeProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderPluginServer will
// result in compilation errors.
type UnsafeProviderPluginServer interface {
	mustEmbedUnimplementedProviderPluginServer()
}

func RegisterProviderPluginServer(s grpc.ServiceRegistrar, srv ProviderPluginServer) {
	s.RegisterService(&ProviderPlugin_ServiceDesc, srv)
}

func _ProviderPlugin_SetLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).SetLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/SetLogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).SetLogger(ctx, req.(*SetLoggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_SetDataDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).SetDataDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/SetDataDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).SetDataDir(ctx, req.(*SetDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_SetCacheDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCacheDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).SetCacheDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/SetCacheDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).SetCacheDir(ctx, req.(*SetCacheDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/Invalidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).Invalidate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_Keep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).Keep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/Keep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).Keep(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderPlugin_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderPluginServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.ProviderPlugin/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderPluginServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderPlugin_ServiceDesc is the grpc.ServiceDesc for ProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.ProviderPlugin",
	HandlerType: (*ProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLogger",
			Handler:    _ProviderPlugin_SetLogger_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ProviderPlugin_Configure_Handler,
		},
		{
			MethodName: "SetDataDir",
			Handler:    _ProviderPlugin_SetDataDir_Handler,
		},
		{
			MethodName: "SetCacheDir",
			Handler:    _ProviderPlugin_SetCacheDir_Handler,
		},
		{
			MethodName: "Invalidate",
			Handler:    _ProviderPlugin_Invalidate_Handler,
		},
		{
			MethodName: "Keep",
			Handler:    _ProviderPlugin_Keep_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _ProviderPlugin_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/plugin/common/plugin.proto",
}

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggerClient interface {
	LoadingMessage(ctx context.Context, in *LoadingMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	EmitLogMessage(ctx context.Context, in *EmitLogMessageRequest, opts ...grpc.CallOption) (*Empty, error)
}

type loggerClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerClient(cc grpc.ClientConnInterface) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) LoadingMessage(ctx context.Context, in *LoadingMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.Logger/LoadingMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) EmitLogMessage(ctx context.Context, in *EmitLogMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.Logger/EmitLogMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
// All implementations must embed UnimplementedLoggerServer
// for forward compatibility
type LoggerServer interface {
	LoadingMessage(context.Context, *LoadingMessageRequest) (*Empty, error)
	EmitLogMessage(context.Context, *EmitLogMessageRequest) (*Empty, error)
	mustEmbedUnimplementedLoggerServer()
}

// UnimplementedLoggerServer must be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (UnimplementedLoggerServer) LoadingMessage(context.Context, *LoadingMessageRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadingMessage not implemented")
}
func (UnimplementedLoggerServer) EmitLogMessage(context.Context, *EmitLogMessageRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitLogMessage not implemented")
}
func (UnimplementedLoggerServer) mustEmbedUnimplementedLoggerServer() {}

// UnsafeLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggerServer will
// result in compilation errors.
type UnsafeLoggerServer interface {
	mustEmbedUnimplementedLoggerServer()
}

func RegisterLoggerServer(s grpc.ServiceRegistrar, srv LoggerServer) {
	s.RegisterService(&Logger_ServiceDesc, srv)
}

func _Logger_LoadingMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadingMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LoadingMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Logger/LoadingMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LoadingMessage(ctx, req.(*LoadingMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_EmitLogMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitLogMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).EmitLogMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Logger/EmitLogMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).EmitLogMessage(ctx, req.(*EmitLogMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Logger_ServiceDesc is the grpc.ServiceDesc for Logger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadingMessage",
			Handler:    _Logger_LoadingMessage_Handler,
		},
		{
			MethodName: "EmitLogMessage",
			Handler:    _Logger_EmitLogMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/plugin/common/plugin.proto",
}
